### ISSUE TITLE
Error 404 on global_sessions_config()

### ISSUE THREAD

**Issue by pythiantech** [Tychobra/polished#87]
I am following the procedure listed [here](https://polished.tech/docs/firebase-setup) and have entered the following information correctly in my `global.R`:

```
polished::global_sessions_config(
  app_name = "my_first_shiny_app",
  api_key = "<your polished.tech secret API key>",
  firebase_config = list(
    apiKey = "<your Firebase API key>",
    authDomain = "<your Firebase auth domain>",
    projectId = "<your Firebase projectId>"
  )
)

```
However when I run the app, I get `Error: 404 - Resource Not Found`. Not sure what's wrong. Here's my session info:

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] waiter_0.1.0         htmlwidgets_1.5.1    shinythemes_1.1.2    shinyjs_1.1         
 [5] shinyWidgets_0.5.3   raster_3.2-2         geojsonio_0.9.2      leafem_0.1.1        
 [9] leaflet.extras_1.0.0 leaflet_2.0.3        sf_0.9-3             rgdal_1.5-8         
[13] maptools_1.0-1       sp_1.4-2             mapedit_0.6.0        mapview_2.7.8       
[17] forcats_0.5.0        stringr_1.4.0        dplyr_1.0.0          purrr_0.3.4         
[21] readr_1.3.1          tidyr_1.1.0          tibble_3.0.1         ggplot2_3.3.1       
[25] tidyverse_1.3.0      shiny_1.4.0.2       

loaded via a namespace (and not attached):
 [1] colorspace_1.4-1         ellipsis_0.3.1           class_7.3-17            
 [4] satellite_1.0.2          base64enc_0.1-3          fs_1.4.1                
 [7] httpcode_0.3.0           rstudioapi_0.11          DT_0.13                 
[10] fansi_0.4.1              lubridate_1.7.8          xml2_1.3.2              
[13] codetools_0.2-16         knitr_1.28               jsonlite_1.6.1          
[16] packrat_0.5.0            broom_0.5.6              dbplyr_1.4.4            
[19] rgeos_0.5-3              png_0.1-7                shinydashboard_0.7.1    
[22] compiler_3.6.3           httr_1.4.1               shinyFeedback_0.2.0     
[25] backports_1.1.7          lazyeval_0.2.2           assertthat_0.2.1        
[28] fastmap_1.0.1            cli_2.0.2                later_1.0.0             
[31] htmltools_0.4.0          tools_3.6.3              gtable_0.3.0            
[34] glue_1.4.1               geojson_0.3.2            apexcharter_0.1.4       
[37] V8_3.0.2                 Rcpp_1.0.4.6             cellranger_1.1.0        
[40] vctrs_0.3.1              crul_0.9.0               nlme_3.1-148            
[43] crosstalk_1.1.0.1        xfun_0.14                rvest_0.3.5             
[46] mime_0.9                 lifecycle_0.2.0          shinycssloaders_0.3     
[49] jqr_1.1.0                scales_1.1.1             hms_0.5.3               
[52] promises_1.1.0           curl_4.3                 yaml_2.2.1              
[55] jose_1.0                 stringi_1.4.6            e1071_1.7-3             
[58] rlang_0.4.6.9000         pkgconfig_2.0.3          shinydashboardPlus_0.7.0
[61] polished_0.0.5.9003      evaluate_0.14            lattice_0.20-41         
[64] tidyselect_1.1.0         magrittr_1.5             R6_2.4.1                
[67] generics_0.0.2           DBI_1.1.0                pillar_1.4.4            
[70] haven_2.3.0              foreign_0.8-75           withr_2.2.0             
[73] units_0.6-6              modelr_0.1.8             crayon_1.3.4            
[76] uuid_0.1-4               KernSmooth_2.23-17       rmarkdown_2.1           
[79] grid_3.6.3               readxl_1.3.1             blob_1.2.1              
[82] reprex_0.3.0             digest_0.6.25            classInt_0.4-3          
[85] webshot_0.5.2            xtable_1.8-4             httpuv_1.5.3.1          
[88] openssl_1.4.1            stats4_3.6.3             munsell_0.5.0           
[91] viridisLite_0.3.0        askpass_1.1   

```

**Comment by merlinoa** [comment]
You need to first create an app on polished.tech named "my_first_shiny_app".  You are getting a 404 error because your app cannot be found on polished.tech.

Please check out https://polished.tech/docs/get-started for step by step instructions.

**Comment by merlinoa** [comment]
Sorry I merged the last branch before an API update was ready for polished.tech, so currently I am updating the polished.tech API to get it back up to date with the master branch of polished.  If you install this branch of polished it should work with the current polished.tech API.

```
remotes::install_github("tychobra/polished", ref = "db_conn")
```

Or if you can wait until tomorrow, I should have the API updates completed on polished.tech.

**Comment by pythiantech** [comment]
@merlinoa thanks for the update. I did try installing the branch mentioned above, but still get the same error. Guess will wait till tomorrow.

**Comment by merlinoa** [comment]
@pythiantech Just to make sure, did you restart your R session after installing the branch above?

**Comment by pythiantech** [comment]
Aah! My bad. The restart did the trick. Thanks again. Btw this is a great package!

**Comment by merlinoa** [comment]
Thanks @pythiantech, and thanks for using polished and polished.tech! 

We are in the middle of some pretty significant updates right now.  Everything should stabilize this week.

**Comment by pythiantech** [comment]
@merlinoa back to the same error :(
Also when I went to my dashboard I found that the app I had created no longer exists, nor does the user. Recreated an app and tried the authentication in shiny. No joy.

**Comment by merlinoa** [comment]
Hi @pythiantech -- can you please upgrade to the latest development version of polished now using:

```
remotes::install_github("tychobra/polished")
```

We made some very significant updates yesterday so you may experience a few temporary issues today and tomorrow as we cleanup potential bugs introduced with the updates.  Sorry for the inconvenience.  We are working to have everything running smoothly ASAP.
